name: LinkCheck

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ '*' ] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: docker://dkhamsing/awesome_bot:latest
      with:
        args: --allow-redirect /github/workspace/README.md